apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ohmyml-ddns-net-tls
spec:
  secretName: ohmyml-ddns-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ohmyml.ddns.net
  dnsNames:
    - ohmyml.ddns.net
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ohmyml.ddns.net
